# Generated by Django 3.1.7 on 2021-04-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210329_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section_one',
            options={'verbose_name': '1. О нас', 'verbose_name_plural': '1. О нас'},
        ),
    ]
