# Generated by Django 3.1.7 on 2021-03-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Faculty')),
                ('study_year', models.CharField(blank=True, max_length=100, verbose_name='Study_year')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('image', models.ImageField(blank=True, upload_to='counrties/images', verbose_name='Country Images')),
                ('slug', models.SlugField(unique=True)),
                ('banner', models.BooleanField(default=False, verbose_name='Banner')),
                ('quantity', models.CharField(max_length=100, verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Faculty')),
                ('study_year', models.CharField(blank=True, max_length=100, verbose_name='Study_year')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='University Name')),
                ('university_city', models.CharField(blank=True, max_length=100, verbose_name='University_city')),
                ('star', models.PositiveIntegerField(default='0', verbose_name='Star')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('map', models.CharField(blank=True, max_length=10000, verbose_name='Map')),
                ('intake', models.CharField(blank=True, max_length=100, verbose_name='All_Intake_months')),
                ('intake_number', models.CharField(default=0, max_length=10, verbose_name='Intake_times')),
                ('video_banner', models.CharField(blank=True, default='IFRAME VIDEO', max_length=1000, verbose_name='Video_banner')),
                ('gallery1', models.ImageField(blank=True, upload_to='university_images/images', verbose_name='University_Image1')),
                ('image2', models.ImageField(blank=True, upload_to='university_images/images', verbose_name='University_Image2')),
                ('image3', models.ImageField(blank=True, upload_to='university_images/images', verbose_name='University_Image3')),
                ('image4', models.ImageField(blank=True, upload_to='university_images/images', verbose_name='University_Image4')),
                ('foundation', models.CharField(blank=True, max_length=100, verbose_name='Foundation')),
                ('bachelor', models.CharField(blank=True, max_length=100, verbose_name='Bachelor')),
                ('masters', models.CharField(blank=True, max_length=100, verbose_name='Masters')),
                ('year_tuition_fee', models.CharField(blank=True, max_length=100, verbose_name='Year_tuition_Fee')),
                ('on_campus_yearly', models.CharField(blank=True, max_length=100, verbose_name='On_campus_yearly')),
                ('slug', models.SlugField(unique=True)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='university.country')),
                ('faculty_bachelor', models.ManyToManyField(blank=True, related_name='faculty_name', to='university.Bachelor', verbose_name='Faculties bachelor')),
                ('masters_bachelor', models.ManyToManyField(blank=True, related_name='faculty_name', to='university.Masters', verbose_name='Masters bachelor')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
