# Generated by Django 3.1.7 on 2021-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelor',
            options={'verbose_name': 'Bachelor', 'verbose_name_plural': 'Bachelor'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страны', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='masters',
            options={'verbose_name': 'Masters', 'verbose_name_plural': 'Masters'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Университеты', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AddField(
            model_name='university',
            name='top_universities',
            field=models.BooleanField(default=False, verbose_name='Top University'),
        ),
    ]
