# Generated by Django 3.1.7 on 2021-03-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_doctors_language_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Faculty')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
            ],
            options={
                'verbose_name': 'Bachelor',
                'verbose_name_plural': 'Bachelor',
            },
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='language',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='study',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='university',
            name='faculty_bachelor',
        ),
        migrations.RemoveField(
            model_name='university',
            name='masters_bachelor',
        ),
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_name', to='university.faculty', verbose_name='Faculty'),
        ),
        migrations.DeleteModel(
            name='Bachelor',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Masters',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
    ]
