# Generated by Django 3.1.7 on 2021-03-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210327_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study_form',
            options={'verbose_name': 'Форма обучения', 'verbose_name_plural': 'Форма обучения'},
        ),
        migrations.AddField(
            model_name='university',
            name='study_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.study_form', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Faculty_name'),
        ),
        migrations.AlterField(
            model_name='study_form',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название Форма обучения'),
        ),
    ]
