# Generated by Django 3.1.7 on 2021-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20210327_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='star',
        ),
        migrations.AlterField(
            model_name='study_form',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='facult', to='university.Faculty'),
        ),
        migrations.AlterField(
            model_name='university',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='faculting', to='university.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='university',
            name='study_form',
            field=models.ManyToManyField(related_name='studing', to='university.Study_form', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='university',
            name='year_tuition_fee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Semester price'),
        ),
    ]
