# Generated by Django 3.1.7 on 2021-03-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20210327_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('need', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Документы для поступления',
                'verbose_name_plural': 'Документы для поступления',
            },
        ),
    ]
