# Generated by Django 3.1.7 on 2021-03-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20210328_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='quantity',
        ),
    ]
