# Generated by Django 3.1.7 on 2021-03-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_remove_country_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty_name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faculty_name'),
        ),
        migrations.AddField(
            model_name='study_form',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название Форма обучения'),
        ),
        migrations.AddField(
            model_name='study_form',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название Форма обучения'),
        ),
        migrations.AddField(
            model_name='university',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='university',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='university',
            name='intake_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='All_Intake_months'),
        ),
        migrations.AddField(
            model_name='university',
            name='intake_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='All_Intake_months'),
        ),
        migrations.AddField(
            model_name='university',
            name='language_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='university',
            name='language_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University_city'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_city_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University_city'),
        ),
    ]
