# Generated by Django 3.1.7 on 2021-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_auto_20210329_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '7.0 Страны', 'verbose_name_plural': '7.0 Страны'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '7.5 Документы для поступления', 'verbose_name_plural': '7.5 Документы для поступления'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': '7.1 Факультет', 'verbose_name_plural': '7.1 Факультет'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': '7.3 Рейтинг', 'verbose_name_plural': '7.3 Рейтинг'},
        ),
        migrations.AlterModelOptions(
            name='study_form',
            options={'verbose_name': '7.2 Форма обучения', 'verbose_name_plural': '7.2 Форма обучения'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': '7.4 Университеты', 'verbose_name_plural': '7.4 Университеты'},
        ),
        migrations.AlterField(
            model_name='country',
            name='banner',
            field=models.BooleanField(default=False, verbose_name='Топ страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, upload_to='counrties/images', verbose_name='Фото страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='need',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='study_year',
            field=models.CharField(blank=True, max_length=100, verbose_name='Период учебы'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг для университета'),
        ),
        migrations.AlterField(
            model_name='university',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='faculting', to='university.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='university',
            name='intake',
            field=models.CharField(blank=True, max_length=100, verbose_name='Месяцы приема'),
        ),
        migrations.AlterField(
            model_name='university',
            name='intake_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Месяцы приема'),
        ),
        migrations.AlterField(
            model_name='university',
            name='intake_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Месяцы приема'),
        ),
        migrations.AlterField(
            model_name='university',
            name='language',
            field=models.CharField(max_length=200, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AlterField(
            model_name='university',
            name='language_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AlterField(
            model_name='university',
            name='language_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='on_campus_yearly',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена/проживание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='top_universities',
            field=models.BooleanField(default=False, verbose_name='Top Университет'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_city_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_city_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='university',
            name='year',
            field=models.CharField(max_length=200, null=True, verbose_name='Университет основан'),
        ),
        migrations.AlterField(
            model_name='university',
            name='year_tuition_fee',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена/семестр'),
        ),
    ]
