# Generated by Django 3.1.7 on 2021-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_auto_20210401_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='on_campus_yearly',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена/проживание'),
        ),
    ]
