# Generated by Django 3.1.7 on 2021-04-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_auto_20210402_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='year_tuition_fee',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена/семестр'),
        ),
    ]
