# Generated by Django 3.1.7 on 2021-04-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_auto_20210403_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, upload_to='university_images/images', verbose_name='University_LOGO'),
        ),
    ]
