# Generated by Django 3.1.7 on 2021-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_remove_university_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='faculting', to='university.Faculty', verbose_name='Факультет'),
        ),
    ]
