# Generated by Django 3.1.7 on 2021-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_university_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('£', '£'), ('€', '€'), ('₽', '₽')], max_length=200, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='university',
            name='year_tuition_fee',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена/год'),
        ),
    ]
