# Generated by Django 3.1.7 on 2021-06-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_auto_20210419_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-id'], 'verbose_name': '7.0 Страны', 'verbose_name_plural': '7.0 Страны'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id'], 'verbose_name': '7.5 Документы для поступления', 'verbose_name_plural': '7.5 Документы для поступления'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['-id'], 'verbose_name': '7.1 Факультет', 'verbose_name_plural': '7.1 Факультет'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-id'], 'verbose_name': '7.3 Рейтинг', 'verbose_name_plural': '7.3 Рейтинг'},
        ),
        migrations.AlterModelOptions(
            name='study_form',
            options={'ordering': ['-id'], 'verbose_name': '7.2 Форма обучения', 'verbose_name_plural': '7.2 Форма обучения'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-id'], 'verbose_name': '7.4 Университеты', 'verbose_name_plural': '7.4 Университеты'},
        ),
        migrations.AlterField(
            model_name='university',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='faculting', to='university.Faculty', verbose_name='Факультет(выберите основные 4-5 факультета)'),
        ),
        migrations.CreateModel(
            name='Faculty_for_Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('content', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_for_forms_requests_created', to='university.university')),
                ('faculty_form', models.ManyToManyField(blank=True, related_name='faculty_f', to='university.Faculty', verbose_name='Факультет(выберите основные 4-5 факультета)')),
            ],
            options={
                'verbose_name': '7.4.1 Faculty_Forms',
                'verbose_name_plural': '7.4.1 Faculty_Forms',
            },
        ),
    ]
