# Generated by Django 3.1.7 on 2021-06-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_auto_20210615_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_for_forms',
            name='title',
        ),
        migrations.AddField(
            model_name='faculty_for_forms',
            name='study_faculty_form',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.study_form'),
        ),
    ]
