# Generated by Django 3.1.7 on 2021-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='advantage/images', verbose_name='Advantage image in webr'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, upload_to='advantage/images', verbose_name='Advantage image in png'),
        ),
    ]
