# Generated by Django 3.1.7 on 2021-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210325_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Name')),
                ('status', models.CharField(blank=True, max_length=1000, verbose_name='Specialist status')),
                ('image', models.ImageField(blank=True, upload_to='specialist/images', verbose_name='Specialist photo')),
            ],
            options={
                'verbose_name': 'Вопросы & Ответы',
                'verbose_name_plural': 'Вопросы & Ответы',
            },
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='advantage/images', verbose_name='Advantage image in webp'),
        ),
    ]
