# Generated by Django 3.1.7 on 2021-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210326_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='image1',
        ),
    ]
