# Generated by Django 3.1.7 on 2021-03-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_advantage_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Advantage'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Advantage'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answers_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answers_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Answers'),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='status_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Specialist status'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='status_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Specialist status'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
    ]
