# Generated by Django 3.1.7 on 2021-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210329_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': '3.2 Преимущества', 'verbose_name_plural': '3.2 Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': '3.1 Вопросы & Ответы', 'verbose_name_plural': '3.1 Вопросы & Ответы'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': '3.0 Специалист', 'verbose_name_plural': '3.0 Специалист'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': '3.3 Отзывы', 'verbose_name_plural': '3.3 Отзывы'},
        ),
        migrations.AlterField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, upload_to='advantage/images', verbose_name='Фото Преимущества'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Название Преимущества'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название Преимущества'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название Преимущества'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answers',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answers_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answers_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='questions',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='questions_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='questions_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, upload_to='specialist/images', verbose_name='Фото Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Профессия Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='status_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Профессия Специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='status_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Профессия Специалиста'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, upload_to='testimonials/images', verbose_name='Фото для отзыва'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя'),
        ),
    ]
