# Generated by Django 3.1.7 on 2021-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Country')),
                ('image', models.ImageField(blank=True, upload_to='counrties/images', verbose_name='Country Images')),
                ('slug', models.SlugField(unique=True)),
                ('banner', models.BooleanField(default=False, verbose_name='Valid news')),
                ('description', models.TextField(verbose_name='Description')),
                ('top_news', models.BooleanField(default=False, verbose_name='Top_news')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
