# Generated by Django 3.1.7 on 2021-03-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210325_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Title'),
        ),
    ]
