# Generated by Django 3.1.7 on 2021-03-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
