# Generated by Django 3.1.7 on 2021-03-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210329_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
