# Generated by Django 3.1.7 on 2021-03-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulting',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявка'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contact_form',
            options={'verbose_name': 'Форма для студентов', 'verbose_name_plural': 'Форма для студентов'},
        ),
    ]
