# Generated by Django 3.1.7 on 2021-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210325_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Phone1'),
        ),
    ]
