# Generated by Django 3.1.7 on 2021-03-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
