# Generated by Django 3.1.7 on 2021-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210329_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulting',
            options={'verbose_name': '2.0 Заявка', 'verbose_name_plural': '2.0 Заявка'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '2.1 Контакты', 'verbose_name_plural': '2.1 Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contact_form',
            options={'verbose_name': '2.2 Форма для студентов', 'verbose_name_plural': '2.2 Форма для студентов'},
        ),
        migrations.AlterField(
            model_name='consulting',
            name='birth_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='city',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Форма оформлена'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='description',
            field=models.TextField(verbose_name='Инфо о себе'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='english',
            field=models.CharField(blank=True, choices=[('Начинающий (А1-А2)', 'Начинающий (А1-А2)'), ('Средний (В1-В2)', 'Средний (В1-В2)'), ('Продвинутый(С1-С2)', 'Продвинутый(С1-С2)')], max_length=1000, verbose_name='Уровень анг.яз'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тел.номер'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='study',
            field=models.CharField(blank=True, choices=[('Бакалавр', 'Бакалавр'), ('Foundation', 'Foundation'), ('Магистратура', 'Магистратура')], max_length=1000, verbose_name='Направления'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='surname',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='take_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Адрес2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Тел.номер'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Доп.Тел.номер'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_time',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='content',
            field=models.CharField(blank=True, max_length=100, verbose_name='Доп.инфо'),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Оформлена заявка'),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='phone',
            field=models.CharField(blank=True, default='+998', max_length=100, verbose_name='Тел.номер'),
        ),
    ]
