# Generated by Django 3.1.7 on 2021-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210401_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulting_uz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=1000, verbose_name='Фамилия')),
                ('birth_date', models.DateTimeField(blank=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=1000, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=1000, verbose_name='Тел.номер')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('english', models.CharField(blank=True, choices=[('Начинающий (А1-А2)', 'Начинающий (А1-А2)'), ('Средний (В1-В2)', 'Средний (В1-В2)'), ('Продвинутый(С1-С2)', 'Продвинутый(С1-С2)')], max_length=1000, verbose_name='Уровень анг.яз')),
                ('study', models.CharField(blank=True, choices=[('Бакалавр', 'Бакалавр'), ('Foundation', 'Foundation'), ('Магистратура', 'Магистратура')], max_length=1000, verbose_name='Направления')),
                ('description', models.TextField(verbose_name='Инфо о себе')),
                ('take_date', models.DateTimeField(blank=True, verbose_name='Дата сдачи')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Форма оформлена')),
            ],
            options={
                'verbose_name': '3.0 Заявка на узб',
                'verbose_name_plural': '3.0 Заявка на узб',
            },
        ),
        migrations.AlterModelOptions(
            name='consulting',
            options={'verbose_name': '2.0 Заявка на рус', 'verbose_name_plural': '2.0 Заявка на рус'},
        ),
    ]
