# Generated by Django 3.1.7 on 2021-04-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210407_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='consulting_uz',
            name='english',
            field=models.CharField(blank=True, choices=[('Boshlang`ich (А1-А2)', 'Boshlang`ich (А1-А2)'), ('O`rtacha (В1-В2)', 'O`rtacha (В1-В2)'), ('Mukammal (С1-С2)', 'Mukammal (С1-С2)')], max_length=1000, verbose_name='Уровень анг.яз'),
        ),
        migrations.AlterField(
            model_name='consulting_uz',
            name='study',
            field=models.CharField(blank=True, choices=[('Bakalavr', 'Bakalavr'), ('Foundation', 'Foundation'), ('Magistratura', 'Magistratura')], max_length=1000, verbose_name='Направления'),
        ),
    ]
