# Generated by Django 3.1.7 on 2021-03-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='students_gallery/images', verbose_name='Gallery photo')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('university', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='university.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery_photos',
            },
        ),
    ]
