# Generated by Django 3.1.7 on 2021-03-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Наши Студенты', 'verbose_name_plural': 'Наши Студенты'},
        ),
    ]
