# Generated by Django 3.1.7 on 2021-03-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20210325_2138'),
        ('students', '0002_auto_20210325_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея Студентов', 'verbose_name_plural': 'Галерея Студентов'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='content',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='university',
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, verbose_name='Name')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.gallery', verbose_name='Gallery')),
                ('university', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='university.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Наши Студенты',
                'verbose_name_plural': 'Наши Студенты',
            },
        ),
    ]
