# Generated by Django 3.1.7 on 2021-03-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210326_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='students',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='students',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='students',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name'),
        ),
    ]
