# Generated by Django 3.1.7 on 2021-04-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_auto_20210329_0822'),
        ('students', '0004_auto_20210329_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': '6.0 Галерея Студентов', 'verbose_name_plural': '6.0 Галерея Студентов'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '6.1 Наши Студенты', 'verbose_name_plural': '6.1 Наши Студенты'},
        ),
        migrations.AddField(
            model_name='students',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='students_gallery/images', verbose_name='Фото галерея студентов'),
        ),
        migrations.AlterField(
            model_name='students',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='students',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='students',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.gallery', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name_uz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='university.university', verbose_name='Университет'),
        ),
    ]
