# Generated by Django 3.1.7 on 2021-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210401_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gallery',
        ),
        migrations.AddField(
            model_name='students',
            name='gallery',
            field=models.ManyToManyField(null=True, related_name='gal', to='students.Gallery'),
        ),
    ]
