# Generated by Django 3.1.7 on 2021-04-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210401_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gallery',
            field=models.ManyToManyField(related_name='gal', to='students.Gallery'),
        ),
    ]
